# theme: jekyll-theme-minimal
title: Philip's Data Science Portfolio
description: Portfolio in Applied Data Science & Sustainability
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
