# theme: jekyll-theme-minimal
title: Philip's Data Science Portfolio
description: Portfolio in Applied Data Science & Sustainability
# remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
