title: Philip's Data Science Portfolio
description: Portfolio in Applied Data Science & Sustainability
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-last-modified-at

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
author: Philip Wehry

url: "https://philiphkw.github.io"
baseurl: "/philipwehry.github.io"